name: freezed_bloc_example
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: any
  json_annotation: ^4.9.0
  hive: ^2.2.3
  freezed_annotation: ^2.4.4
  go_router: ^16.2.4
  hive_flutter: ^1.1.0
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  very_good_analysis: ^9.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: any
  build_runner: ^2.5.4
  freezed: ^2.4.7
  json_serializable: ^6.9.0
  go_router_builder: ^3.0.0
  flutter_lints: any
  hive_generator: ^2.0.1

flutter:

  uses-material-design: true
